import pathlib
# firstloop = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/firstloop_run2_mismatches.txt').read_text().split())
firstloop_1 = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/firstloop_run3_mismatches.txt').read_text().split())
firstloop_2 = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/firstloop_run4_mismatches.txt').read_text().split())
# base = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/baseagent_run2_mismatches.txt').read_text().split())
# print('firstloop count', len(firstloop))
print('firstloop_run3 count', len(firstloop_1))
print('firstloop_run4 count', len(firstloop_2))
# print('base count', len(base))
# print('overlap', len(firstloop & base))
print('overlap', len(firstloop_1 & firstloop_2))
# print('firstloop-only', len(firstloop - base))
print('firstloop_run3-only', len(firstloop_1 - firstloop_2))
# print('base-only', len(base - firstloop))
print('firstloop_run4-only', len(firstloop_2 - firstloop_1))
# print('overlap list:\n', sorted(firstloop & base))
print('overlap list:\n', sorted(firstloop_1 & firstloop_2))
# print('first-only list:\n', sorted(firstloop - base))
print('firstloop_run3-only', sorted(firstloop_1 - firstloop_2))
# print('base-only list:\n', sorted(base - firstloop))
print('firstloop_run4-only', sorted(firstloop_2 - firstloop_1))