import pathlib
# firstloop = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/firstloop_run2_mismatches.txt').read_text().split())
BaseMADTEST = set(int(line.strip()) for line in pathlib.Path('Exp\check_mismatches\Qwen2.5_BaseMAD.txt').read_text().split())
Qwen3BaseMAD = set(int(line.strip()) for line in pathlib.Path('Exp\check_mismatches\Qwen3_BaseMAD.txt').read_text().split())
# base = set(int(line.strip()) for line in pathlib.Path('Exp/check_mismatches/baseagent_run2_mismatches.txt').read_text().split())
# print('firstloop count', len(firstloop))
print('BaseMADTEST count', len(BaseMADTEST))
print('Qwen3BaseMA count', len(Qwen3BaseMAD))
# print('base count', len(base))
# print('overlap', len(firstloop & base))
print('overlap', len(BaseMADTEST & Qwen3BaseMAD))
# print('firstloop-only', len(firstloop - base))
print('BaseMADTEST-only', len(BaseMADTEST - Qwen3BaseMAD))
# print('base-only', len(base - firstloop))
print('Qwen3BaseMAD-only', len(Qwen3BaseMAD - BaseMADTEST))
# print('overlap list:\n', sorted(firstloop & base))
print('overlap list:\n', sorted(BaseMADTEST& Qwen3BaseMAD))
# print('first-only list:\n', sorted(firstloop - base))
print('BaseMADTEST-only', sorted(BaseMADTEST- Qwen3BaseMAD))
# print('base-only list:\n', sorted(base - firstloop))
print('Qwen3BaseMAD-only', sorted(Qwen3BaseMAD - BaseMADTEST))